import 'dotenv/config';
import mysql from 'mysql2/promise';

async function main() {
  const dbUrl = process.env.DATABASE_URL || 'mysql://root:@localhost:3306/test_temam';
  const conn = await mysql.createConnection(dbUrl);

  const [rows]: any = await conn.query('SELECT id, programData FROM mosque_requests WHERE id = 98');
  if (rows.length === 0) {
    console.error('Request 98 not found');
    process.exit(1);
  }

  let pData = rows[0].programData;
  if (typeof pData === 'string') {
    try { pData = JSON.parse(pData); } catch (e) {}
  }
  pData = pData || {};
  pData.sedanaExecution = pData.sedanaExecution || {};

  // 35 days ago timestamp
  const backdateStr = new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString();
  const backdateShort = backdateStr.split('T')[0];

  // 1. Ensure inward order has stock for all 3 items (477: عامل نظافة, 478: صابون سائل, 479: صابون رغوة)
  const inwardOrders = [
    {
      id: "IN-98-1790114911818",
      orderNumber: "IN-98-01",
      orderDate: backdateShort,
      receivedBy: "يحيى (حساب لمتابعة المنصة)",
      referenceType: "purchase_order",
      referenceNumber: "PO-98-2026-04",
      disbursementOrderId: 164,
      disbursementOrderNumber: "DO-2026-0153",
      disbursementExecutedAt: "2026-09-22T21:59:18.000Z",
      supplierInvoiceNumber: "",
      supplierName: "شركة نظم لتقنية المعلومات",
      notes: "توريد كامل الدفعة الأولى لكافة بنود الطلب",
      items: [
        {
          id: "477",
          itemName: "عامل نظافة متفرغ للمسجد",
          quantity: 5,
          unit: "شهر"
        },
        {
          id: "478",
          itemName: "صابون سائل للأيدي",
          quantity: 10,
          unit: "جالون"
        },
        {
          id: "479",
          itemName: "صابون رغوة للمغاسل",
          quantity: 6,
          unit: "عبوة"
        }
      ],
      createdBy: 44,
      createdByName: "يحيى (حساب لمتابعة المنصة)",
      createdAt: backdateStr
    }
  ];

  pData.sedanaExecution.inwardOrders = inwardOrders;

  // 2. Outbound orders:
  // OUT-98-01: Confirmed 35 days ago (so its cycle has ended and next cycle is DUE now)
  pData.sedanaExecution.outboundOrders = [
    {
      id: "OUT-98-1790184702752",
      orderNumber: "OUT-98-01",
      scheduledDate: backdateShort,
      periodLabel: "الدفعة الدورية (شهري) - دفعة رقم 1",
      outboundMethod: "direct_imam",
      recipientName: "إمام المسجد",
      recipientRole: "إمام المسجد",
      recipientPhone: "0500000000",
      deliveryLocation: "جامع العطاء  - ضمك - خميس مشيط",
      disbursementVoucherCode: "DV-SED-98-01",
      status: "pending_receipt",
      isAutoGenerated: true,
      notes: "تم صرف الدفعة الأولى سابقاً",
      items: [
        {
          id: "478",
          itemName: "صابون سائل للأيدي",
          quantity: 4,
          unit: "جالون",
          frequency: "شهري"
        }
      ],
      linkedDeliveryId: null,
      confirmation: null,
      createdBy: null,
      createdByName: "النظام (جدولة آلية)",
      createdAt: backdateStr,
      confirmedBySupervisorAt: backdateStr,
      confirmedBySupervisorId: 1,
      confirmedBySupervisorName: "مدير النظام"
    }
  ];

  // 3. Update request_stage_tracking
  try {
    await conn.query(
      `UPDATE request_stage_tracking SET startedAt = ? WHERE requestId = 98 AND stageCode = 'execution'`,
      [new Date(Date.now() - 35 * 24 * 60 * 60 * 1000)]
    );
    console.log('Stage tracking startedAt backdated to 35 days ago');
  } catch (e) {
    console.log('Stage tracking skipped:', e);
  }

  // 4. Save updated programData
  await conn.query(
    'UPDATE mosque_requests SET programData = ? WHERE id = 98',
    [JSON.stringify(pData)]
  );

  console.log('Successfully updated request 98 in DB: items backdated 35 days ago and stock available for testing!');
  await conn.end();
}

main().catch(console.error);
