import { appRouter } from "../server/routers";

async function main() {
  const ctx = {
    user: { id: 1, username: "admin", role: "admin", name: "مدير النظام" },
    req: {} as any,
    res: {} as any,
  };
  const caller = appRouter.createCaller(ctx);

  console.log("Calling sedanaExecution.getVirtualInventory for requestId 98...");
  const inventory: any = await caller.sedanaExecution.getVirtualInventory({ requestId: 98 });
  console.log("Inventory keys:", Object.keys(inventory));
  console.log("Inventory inventoryItems array length:", inventory.inventoryItems?.length);
  if (inventory.inventoryItems) {
    console.log("First item:", inventory.inventoryItems[0]);
  }

  console.log("Outbound orders:", inventory.outboundOrders?.length);
  inventory.outboundOrders?.forEach((o: any) => {
    console.log(`Order: ${o.orderNumber}, Status: ${o.status}, isAuto: ${o.isAutoGenerated}, period: ${o.periodLabel}, items:`, o.items);
  });

  process.exit(0);
}

main().catch(err => {
  console.error("Error:", err);
  process.exit(1);
});
